# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
jobs:
  include:
    - language: node_js
      node_js:
        - 17
    - language: python
      python: 3.7
      install:
          - pip install setuptools==60.9.0 # https://github.com/pypa/setuptools/issues/3293
          - pip install OctoPrint # Need OctoPrint to satisfy req's of `__init__.py`
          - pip install coverage coveralls
          - pip install -r requirements.txt
      script:
        - coverage run -m unittest discover -p "*_test.py"
      after_success:
        - coveralls
notifications:
  email:
    - smartin015@gmail.com
env:
  - TRAVIS_CI=1 # setup.py requires particular steps for octoprint vs CI environment
